---
title: "Homework 9"
author: "Anthony Ferraro"
output: 
  html_document:
    code_folding: hide
    linkcolor: blue
    urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.align = "center", out.width = "50%", warning = FALSE, message = FALSE)

library(tidyverse)
library(knitr)

theme_set(theme_minimal())

library(babynames)
data(babynames)
```


#### Converting Proportions into Percentages
```{r}
knitr::kable(babynames %>%
  mutate(prop_percent = (prop * 100)) %>%
  head(n = 6))
```

^[Question 1 Complete]


#### Adding a "Percent in Year" Column
```{r}
perc_babynames = babynames %>%
  mutate(prop_percent = (prop * 100))

knitr::kable(perc_babynames %>%
  mutate(prop_percent = round(prop * 100, 2),
         percent_year = str_glue("{prop_percent} % in {year}")) %>%
  head(6))
```

^[Question 2 Complete]


#### Filtering the Data to One Name and Sex
```{r}
str_babynames = perc_babynames %>%
  mutate(prop_percent = round(prop * 100, 2),
         percent_year = str_glue("{prop_percent} % in {year}"))

knitr::kable(str_babynames %>%
  filter(name == "Mary" & sex == "F") %>%
  head(n = 6))
```

^[Question 3 Complete]



#### Selecting 5 Random Rows From the Data
```{r}
filtered_babynames = str_babynames %>%
  filter(name == "Mary" & sex == "F")

set.seed(720)

random_sample <- filtered_babynames %>%
  slice_sample(n = 5) %>%
  arrange(year)

knitr::kable(random_sample)
```

^[Question 4 Complete]



#### Making one Flattened String
```{r}
percent_strings = random_sample %>%
  pull(percent_year)

flattened_string = str_flatten(percent_strings, ", ", last = ", and ")

str_view(flattened_string)
```

^[Question 5 Complete]


#### Making a Final String
```{r results = "asis"}
final_string = str_glue("Out of all female names, the name Mary represented {flattened_string}")

cat(final_string)
```

^[Question 6 Complete]

















